version: "3.7"
services:
  sre_darillium:
    container_name: sre_darillium
    image: sre/sre_darillium:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/cred:/cred
    command: "go run upload_cve_to_bucket.go && /bin/bash"
    environment:
      - GOLANG_SAMPLES_BUCKET
      - GOLANG_SAMPLES_PROJECT_ID
      - GOOGLE_APPLICATION_CREDENTIALS

